import { describe, expect, it } from 'vitest';
import { aead as webCryptoAead } from '../core/aead.js';
import { fromBase64Url, toBase64Url } from '../core/bytes.js';
import { nodeAead } from '../runtime/node-aead.js';
import {
  peekSealedTokenAppId,
  peekSealedTokenUserKey,
  peekSealedTokenVersion,
  unwrapSealedToken,
  wrapSealedToken,
} from './sealed-token.js';

// Deterministic Random stub that always returns the fixed IV
const FIXED_IV = new Uint8Array(12).fill(1);
const fixedRandom = {
  bytes: (_n: number) => new Uint8Array(FIXED_IV),
  uuid: () => '00000000-0000-4000-8000-000000000000',
};

const PAYLOAD = {
  appId: 'app_abc',
  tossUserKey: 'u_42',
  tossAt: 'TOSS_AT_OPAQUE',
  tossRt: 'TOSS_RT_OPAQUE',
  tossAtExp: 1735689600,
  issuedAt: 1735686000,
  tokenType: 'access' as const,
};

// Wire format: version(1) || appIdLen(1) || appId(n) || userKeyLen(1) || userKey(m) || iv(12) || ciphertext || tag(16)
// PAYLOAD has appId='app_abc' (7 bytes) and tossUserKey='u_42' (4 bytes), so:
//  - byte 0:        version
//  - byte 1:        appIdLen = 7
//  - bytes 2..8:    appId
//  - byte 9:        userKeyLen = 4
//  - bytes 10..13:  userKey
//  - bytes 14..25:  iv (12 bytes)
//  - bytes 26..-17: ciphertext
//  - bytes -16..:   tag
const APPID_HINT_OFFSET = 2;
const USERKEY_HINT_OFFSET = 10;

// Golden vector — locked via self-bootstrapping (see below in 'golden vectors' suite).
// Generated by running wrapSealedToken with nodeAead + fixedRandom (fixed IV = 0x01 * 12),
// sealingKey = Uint8Array(32).fill(7), and PAYLOAD.tokenType = 'access'.
// DO NOT change this string without updating the wire format, AEAD parameters, or the
// AAD (which now binds tokenType — changing it rotates the ciphertext + tag tail).
const GOLDEN_TOKEN =
  'ait_AQdhcHBfYWJjBHVfNDIBAQEBAQEBAQEBAQENw-jH4PaILOv2vVEAaBFTy9k41mz4SGANQiYQLdFPmfiQfe-oIaesfAYneLI_mru0Ob1NDu2gHvYd6FiXc9DQi8t8RGG_RX8XeiNC_2tSywzdN2hMmlp8eXQ73ZrssH1-nWvS1bc-9wU4QZxWgnrYKkXvEboZfubFx8JQu1Oor285m3bhJLf1Tuv1PQclbaZ39Qlzc7Q_xUaxUlWDVTuAQ5f8t3OWdY_6xMebMAw';

describe('wrapSealedToken', () => {
  const sealingKey = new Uint8Array(32).fill(7);

  it('produces ait_-prefixed base64url with version byte 1', async () => {
    const token = await wrapSealedToken({
      sealingKey,
      sealingKeyVersion: 1,
      payload: PAYLOAD,
    });
    expect(token).toMatch(/^ait_[A-Za-z0-9_-]+$/);
    const buf = fromBase64Url(token.slice(4));
    expect(buf[0]).toBe(1);
    expect(buf.length).toBeGreaterThan(30);
  });

  it('different calls produce different IVs and ciphertexts', async () => {
    const t1 = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    const t2 = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    expect(t1).not.toBe(t2);
  });
});

describe('unwrapSealedToken', () => {
  const sealingKey = new Uint8Array(32).fill(7);

  it('roundtrips a wrapped token', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    const got = await unwrapSealedToken({
      token: tok,
      resolveKey: (version) => {
        expect(version).toBe(1);
        return sealingKey;
      },
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'access',
    });
    expect(got).toEqual(PAYLOAD);
  });

  it('rejects tampered ciphertext', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    const body = fromBase64Url(tok.slice(4));
    // Flip a byte just before the tag — safely inside ciphertext.
    const idx = body.length - 16 - 1;
    body[idx] = (body[idx]! ^ 0x01) & 0xff;
    const tampered = `ait_${toBase64Url(body)}`;
    await expect(
      unwrapSealedToken({
        token: tampered,
        resolveKey: () => sealingKey,
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
  });

  it('rejects swap to different app via expectedAppId AAD mismatch', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    await expect(
      unwrapSealedToken({
        token: tok,
        resolveKey: () => sealingKey,
        expectedAppId: 'app_other',
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
  });

  it('rejects token without ait_ prefix', async () => {
    await expect(
      unwrapSealedToken({
        token: 'notait_abc',
        resolveKey: () => sealingKey,
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_BAD_FORMAT/);
  });

  it('rejects cross-version replay (v1 wrapper read with v2 key resolver)', async () => {
    const v1Key = new Uint8Array(32).fill(7);
    const v2Key = new Uint8Array(32).fill(9);
    const tok = await wrapSealedToken({
      sealingKey: v1Key,
      sealingKeyVersion: 1,
      payload: PAYLOAD,
    });
    const body = fromBase64Url(tok.slice(4));
    body[0] = 2;
    const forged = `ait_${toBase64Url(body)}`;
    await expect(
      unwrapSealedToken({
        token: forged,
        resolveKey: (v) => (v === 2 ? v2Key : v1Key),
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
  });

  it('rejects token-type confusion: refresh wrapper read as access (AAD mismatch)', async () => {
    const refreshTok = await wrapSealedToken({
      sealingKey,
      sealingKeyVersion: 1,
      payload: { ...PAYLOAD, tokenType: 'refresh' },
    });
    await expect(
      unwrapSealedToken({
        token: refreshTok,
        resolveKey: () => sealingKey,
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
    // ...but unwraps fine with the matching type.
    const ok = await unwrapSealedToken({
      token: refreshTok,
      resolveKey: () => sealingKey,
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'refresh',
    });
    expect(ok.tokenType).toBe('refresh');
  });

  it('peeks userKey hint without decrypting', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    expect(peekSealedTokenUserKey(tok)).toBe('u_42');
  });

  it('rejects tampered userKey hint', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    const buf = fromBase64Url(tok.slice(4));
    buf[USERKEY_HINT_OFFSET] = (buf[USERKEY_HINT_OFFSET]! ^ 0x01) & 0xff;
    const forged = `ait_${toBase64Url(buf)}`;
    await expect(
      unwrapSealedToken({
        token: forged,
        resolveKey: () => sealingKey,
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
  });
});

describe('peekSealedTokenAppId', () => {
  const sealingKey = new Uint8Array(32).fill(7);

  it('reads appId from preamble without decrypting', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    expect(peekSealedTokenAppId(tok)).toBe(PAYLOAD.appId);
  });

  it('throws on bad format', () => {
    expect(() => peekSealedTokenAppId('xxx')).toThrow(/SEALED_TOKEN_BAD_FORMAT/);
  });

  it('rejects tampered appId hint (preamble byte vs expectedAppId mismatch)', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    const buf = fromBase64Url(tok.slice(4));
    buf[APPID_HINT_OFFSET] = (buf[APPID_HINT_OFFSET]! ^ 0x01) & 0xff;
    const forged = `ait_${toBase64Url(buf)}`;
    await expect(
      unwrapSealedToken({
        token: forged,
        resolveKey: () => sealingKey,
        expectedAppId: PAYLOAD.appId,
        expectedTokenType: 'access',
      }),
    ).rejects.toThrow(/SEALED_TOKEN_TAMPERED/);
  });
});

describe('peekSealedTokenVersion', () => {
  const sealingKey = new Uint8Array(32).fill(7);

  it('returns the version byte without decrypting', async () => {
    const tok = await wrapSealedToken({ sealingKey, sealingKeyVersion: 1, payload: PAYLOAD });
    expect(peekSealedTokenVersion(tok)).toBe(1);
  });

  it('throws on bad format', () => {
    expect(() => peekSealedTokenVersion('xxx')).toThrow(/SEALED_TOKEN_BAD_FORMAT/);
  });
});

describe('golden vectors', () => {
  const sealingKey = new Uint8Array(32).fill(7);

  it('nodeAead + fixed IV produces the locked golden token', async () => {
    const token = await wrapSealedToken({
      sealingKey,
      sealingKeyVersion: 1,
      payload: PAYLOAD,
      random: fixedRandom,
      aead: nodeAead,
    });
    expect(token).toBe(GOLDEN_TOKEN);
  });

  it('nodeAead unwraps the golden token to recover the original payload', async () => {
    const got = await unwrapSealedToken({
      token: GOLDEN_TOKEN,
      resolveKey: () => sealingKey,
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'access',
      aead: nodeAead,
    });
    expect(got).toEqual(PAYLOAD);
  });

  it('webCryptoAead unwraps the golden token (Node→WebCrypto interop)', async () => {
    const got = await unwrapSealedToken({
      token: GOLDEN_TOKEN,
      resolveKey: () => sealingKey,
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'access',
      aead: webCryptoAead,
    });
    expect(got).toEqual(PAYLOAD);
  });

  it('webCryptoAead wraps and nodeAead unwraps (WebCrypto→Node interop)', async () => {
    const token = await wrapSealedToken({
      sealingKey,
      sealingKeyVersion: 1,
      payload: PAYLOAD,
      random: fixedRandom,
      aead: webCryptoAead,
    });
    const got = await unwrapSealedToken({
      token,
      resolveKey: () => sealingKey,
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'access',
      aead: nodeAead,
    });
    expect(got).toEqual(PAYLOAD);
  });

  it('nodeAead wraps and webCryptoAead unwraps (Node→WebCrypto interop via wrap)', async () => {
    const token = await wrapSealedToken({
      sealingKey,
      sealingKeyVersion: 1,
      payload: PAYLOAD,
      random: fixedRandom,
      aead: nodeAead,
    });
    const got = await unwrapSealedToken({
      token,
      resolveKey: () => sealingKey,
      expectedAppId: PAYLOAD.appId,
      expectedTokenType: 'access',
      aead: webCryptoAead,
    });
    expect(got).toEqual(PAYLOAD);
  });
});
