import { describe, expect, it } from 'vitest';
import { aead as webCryptoAead } from '../core/aead.js';
import { fromUtf8 } from '../core/bytes.js';
import { nodeAead } from '../runtime/node-aead.js';
import { decryptColumn, encryptColumn } from './encryption.js';

const FIXED_IV = new Uint8Array(12).fill(2);
const fixedRandom = {
  bytes: (_n: number) => new Uint8Array(FIXED_IV),
  uuid: () => '00000000-0000-4000-8000-000000000000',
};

// Golden vector for encryption — locked via self-bootstrapping.
// Generated by encryptColumn with nodeAead + fixedRandom, key=0x42*32, aad='app_xyz', plaintext=PEM stub.
// DO NOT change without updating the wire format.
const GOLDEN_CIPHERTEXT_HEX =
  '020202020202020202020202dfc82b2ff1be12c4e4e4b36198afe5be9b5b318ecef040fc2abe344cf0d721678771c34f51ed991f91c88091f7a906357550a303947e682a2a1e5e6b5c17bf23a592d22d4c23759edd0226d8e126011ede3c7f82cfc07d';

describe('column encryption', () => {
  const key = new Uint8Array(32).fill(0x42);
  const plaintext = fromUtf8(
    '-----BEGIN PRIVATE KEY-----\nMIIBVwIBADANBg...\n-----END PRIVATE KEY-----',
  );
  const aad = fromUtf8('app_xyz');

  it('roundtrips encrypt → decrypt', async () => {
    const enc = await encryptColumn({ key, plaintext, aad });
    const out = await decryptColumn({ key, ciphertext: enc, aad });
    // Compare byte-by-byte
    expect(out.length).toBe(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
      expect(out[i]).toBe(plaintext[i]);
    }
  });

  it('fails when AAD differs', async () => {
    const enc = await encryptColumn({ key, plaintext, aad });
    await expect(
      decryptColumn({ key, ciphertext: enc, aad: fromUtf8('different') }),
    ).rejects.toThrow();
  });

  it('fails when key differs', async () => {
    const enc = await encryptColumn({ key, plaintext, aad });
    await expect(
      decryptColumn({ key: new Uint8Array(32).fill(0xff), ciphertext: enc, aad }),
    ).rejects.toThrow();
  });

  it('produces different ciphertexts for the same input (random IV)', async () => {
    const a = await encryptColumn({ key, plaintext, aad });
    const b = await encryptColumn({ key, plaintext, aad });
    // Different IVs means different ciphertexts (random IV)
    let differs = false;
    for (let i = 0; i < Math.min(a.length, b.length); i++) {
      if (a[i] !== b[i]) {
        differs = true;
        break;
      }
    }
    expect(differs).toBe(true);
  });

  it('rejects keys not 32 bytes', async () => {
    await expect(encryptColumn({ key: new Uint8Array(16), plaintext, aad })).rejects.toThrow(
      /32 bytes/,
    );
  });
});

describe('column encryption — golden vectors', () => {
  const key = new Uint8Array(32).fill(0x42);
  const plaintext = fromUtf8(
    '-----BEGIN PRIVATE KEY-----\nMIIBVwIBADANBg...\n-----END PRIVATE KEY-----',
  );
  const aad = fromUtf8('app_xyz');

  function hexToUint8(hex: string): Uint8Array {
    const out = new Uint8Array(hex.length / 2);
    for (let i = 0; i < out.length; i++) {
      out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    }
    return out;
  }

  it('nodeAead + fixed IV produces the locked golden ciphertext', async () => {
    const enc = await encryptColumn({ key, plaintext, aad, random: fixedRandom, aead: nodeAead });
    const hex = Array.from(enc)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
    expect(hex).toBe(GOLDEN_CIPHERTEXT_HEX);
  });

  it('nodeAead decrypts the golden ciphertext', async () => {
    const enc = hexToUint8(GOLDEN_CIPHERTEXT_HEX);
    const out = await decryptColumn({ key, ciphertext: enc, aad, aead: nodeAead });
    expect(out.length).toBe(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
      expect(out[i]).toBe(plaintext[i]);
    }
  });

  it('webCryptoAead decrypts the golden ciphertext (Node→WebCrypto interop)', async () => {
    const enc = hexToUint8(GOLDEN_CIPHERTEXT_HEX);
    const out = await decryptColumn({ key, ciphertext: enc, aad, aead: webCryptoAead });
    expect(out.length).toBe(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
      expect(out[i]).toBe(plaintext[i]);
    }
  });

  it('webCryptoAead encrypts and nodeAead decrypts (WebCrypto→Node interop)', async () => {
    const enc = await encryptColumn({
      key,
      plaintext,
      aad,
      random: fixedRandom,
      aead: webCryptoAead,
    });
    const out = await decryptColumn({ key, ciphertext: enc, aad, aead: nodeAead });
    expect(out.length).toBe(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
      expect(out[i]).toBe(plaintext[i]);
    }
  });

  it('nodeAead encrypts and webCryptoAead decrypts (Node→WebCrypto interop via encrypt)', async () => {
    const enc = await encryptColumn({ key, plaintext, aad, random: fixedRandom, aead: nodeAead });
    const out = await decryptColumn({ key, ciphertext: enc, aad, aead: webCryptoAead });
    expect(out.length).toBe(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
      expect(out[i]).toBe(plaintext[i]);
    }
  });
});
